### PR TITLE
Header of the IR result table now have dynamic elements that allow to increase and decrease ratio

### LINKED ISSUE #849: Dynamic elements in the IR result table does not work properly
In atlas, we can change the rate and proportion dynamically:
f6c34b92-cb1a-445a-a11c-c4df2d45d090

In Arachne we can't, there are only static elements:
15ffda7d-397f-4a8a-99f0-86b369ea870b

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #849

### CODE REVIEW

File: src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx [hunk 1]
```diff
@@ -73,12 +96,17 @@ export default function SummaryIncidence({ resultInfo = [], className }) {
           </div>}
           field={'timeAtRisk'}
         />
-        <TableCellText
+        <DynamicCell
           header={<div {...classes('header')}>
-            <span>Rate [+|-]</span>
-            <span {...classes('header-subtitle')}>per 1k years</span>
+            <span>Rate [
+              <span {...classes('span-active')} onClick={() => changeRatio(10)}> + </span>
```
Comment (dmitrys-odysseus) [inline src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx:102]: Is it always x10 or /10? Or is it currently possible to change ratio in arbitrary way?

Comment (ssuvorov-fls) [reply src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx:102]: It is always x10 or /10

Comment (dmitrys-odysseus) [reply src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx:102]: then, just storing decimal exponent value and doing +1/-1 on it would be much more concise and would not require divisions.

Comment (ssuvorov-fls) [reply src/modules/AnalysisExecution/components/SubmissionCodeViewer/ResultFile/components/Summary/Incidence/presenter.jsx]: agree, fixed

**Review by dmitrys-odysseus — APPROVED** [review]
